define({
  root: ({
    labelDelete: "Delete",
	labelLoad: "Load Map States", 
	labelSave: "Create Map State", 
	labelRestore: "Restore to Default",
	labelAdvanced: "Advanced",
	errorNameExist: "Configuration exists!",
	errorNameEmpty: "No Configuration found for %mapName%",
	errSaveFailure: "Failed to save the current Configuration for %mapName%",
	errLoadFailure: "Failed to load the saved Configuration for %mapName%",
	errDeleteFailure: "Failed to delete the saved Configuration for %mapName%",
	msgSaveSuccess: "Configuration %configName% %savedPreferences% saved for %mapName%",
	msgStateStatus: "Last Configuration saved on %date%",
	msgLoadSuccess: "Configuration %configName% loaded for %mapName%",
	msgDeleteSuccess: "Configuration %configName% deleted for %mapName%",
	configComboBoxDefault: 'Select or Type a name to save',	
	groupMultiSelectDefault: 'Select a group or groups to share',
	indivMultiSelectDefault: 'Select individuals to share',
	shareToSelectDefault: 'Private',
	portalUserFilter: 'role: org_user OR role: org_admin OR role: org_publisher',
	desptTextareaPlaceHolder: 'Type description for new mapstate', 
	advSettingLabel: 'Advanced Setting:',
	shareToLabel: 'Share To:',
	advSettingList: ['extent', 'layers', 'graphicsLayers', 'layerDef'],
	advSettingLabels: ['Map Extent', 'Layers', 'Graphics', 'Filters'],
	operations: ['new', 'update', 'delete'],
	shareTo: ['Organization', 'Groups And/or Individuals', 'Private'],
	configTabTitles: ['Org Map State', 'Shared Map State', 'My Map State'],
	filterLabel: "Search map states by name:", 
	sortByOption_name: "Name", 
	sortByOption_date: "Date", 
	sortByOption_owner: "Owner",
	sortByLabel: "sort by:", 
	sortOrderTitle: "sort order", 
	filterSortApplyButtonLabel: "Apply", 
	msgOverwriteConfirm: 'You are about to Overwrite the map State.\nPress OK to continue or Cancel to cancel the operation.',
	msgDeleteConfirm: 'You are about to Delete the map State.\nPress OK to continue or Cancel to cancel the operation.',
    _widgetLabel: "Advanced Save"
  })
});